name: Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v9.0.0
        with:
          globs: "**/*.md"
